### ISSUE TITLE
Bifrost files from cache not detected as assets

### ISSUE THREAD

**Issue by davidkydd** [Azure/azure-batch-maya#24]
Maya doesn't seem to be reporting cached Bifröst data to the _get_caches function (the files do not show up in the assets list automatically).

For the scene in which this was observed, the following conditional from assets.py _get_caches() ~ln514 always evaluates to true and the "continue" was executed for all 5 bifrost container files, preventing the files being added as an asset:

```python
if not maya.get_attr(container + ".enableDiskCache"):
    continue
```

**Comment by annatisch** [comment]
Should be resolved in v0.17
