### ISSUE TITLE
Investigate versioning of getpip.py script

### ISSUE THREAD

**Issue by davidkydd** [Azure/azure-batch-maya#26]
Currently the plugin checks for the existence of \Temp\azure-batch-maya\getpip.py and if it doesn't exist it downloads a version from "https://bootstrap.pypa.io/get-pip.py"

As such we have a dependency on a "floating" version of pip, and any breaking changes in the version available at the above link will get passed down.

**Comment by annatisch** [comment]
No longer necessary as we bundle getpip with v0.17
