### ISSUE TITLE
Mask batch and storage keys in Azure Batch Maya plugin

### ISSUE THREAD

**Issue by richardlock** [Azure/azure-batch-maya#32]
Hi,

Is it possible to mask the Azure batch and storage keys from being displayed to users in the Azure Batch Maya plugin?  We would like to roll this out in our student labs, but would like to hide these keys so that users cannot access the keys which have been entered for use elsewhere.  If the box was treated similar to a password field, it would mask out the actual value after configuring it.

Thanks, Richard

**Comment by davidkydd** [comment]
Hi Richard, apologies for the delayed response.

Are your students enrolled in AAD (Azure Active Directory)? If so you could move to a forked version of the repo which includes AAD support. Users then login to the plugin with their AAD username + password and permissions are managed within AAD, meaning you do not need to share any keys. Let me know if this approach would work for you and I can guide you through it.

As we plan to move to AAD support exclusively, and remove support for shared key authentication, the change you suggest, while a good one, is not likely to be implemented in the near term. 

Also please let me know if the removal of share key auth and the requirement of signing in with AAD auth would be a significant problem for your scenario.

Thanks,
David

**Comment by richardlock** [comment]
Hi David,

Thanks.  Using AAD would work for us and would remove the need for shared key auth.

Thanks, Richard

**Comment by davidkydd** [comment]
Great - AAD branch is at: 
https://github.com/davidkydd/azure-batch-maya/tree/aad

Please open an issue on that branch if you encounter any problems - you should be able to just:
1) unload the old plugin 
2) close maya
3) reopen maya and load the new plugin

David

**Comment by richardlock** [comment]
Thanks David
