### ISSUE TITLE
Additional VM types for Env: Use VM Type

### ISSUE THREAD

**Issue by richardlock** [Azure/azure-batch-maya#33]
Hi,

Is it possible to use other VM Types with the azure-batch-maya plugin beyond Standard_A*/D*/D*_v2?  The dropdown box in Maya does not show any other options, but we'd like to test against the F and Fv2 series for rendering at lower cost.

Thanks, Richard

**Comment by psyrus** [comment]
If you edit your local file to include the other SKUs, you can put pretty much whatever you want in there
https://github.com/Azure/azure-batch-maya/blob/master/azure_batch_maya/scripts/tools/skus.json

You just need the SKU "code" which I believe can be found here:
https://docs.microsoft.com/en-us/azure/virtual-machines/windows/sizes-general

**Comment by richardlock** [comment]
Thanks, that's great.
