### ISSUE TITLE
Couldn't load plugin in both Maya 2017 and 2018

### ISSUE THREAD

**Issue by hirtanak** [Azure/azure-batch-maya#8]
Latest Maya 2017 couldn't load plugin
// Error: file: C:/Program Files/Autodesk/Maya2017/scripts/others/pluginWin.mel line 767:  (AzureBatch)

This behaviour could show in Maya 2017 Japanese and English. In addition, Maya 2018 Japanese and English (different line in error)

	global string $defaultPluginBrowseDir;
	$defaultPluginBrowseDir = `getDir $theFile`;
	// Set the file rule - this makes sure that future calls to browse
	// start from the same place
	if ( catch( `loadPlugin $theFile` ) ) {
 		string $warningMsg = (uiRes("m_pluginWin.kCouldNotLoadPlugin"));
 		$warningMsg =`format -s $theFile $warningMsg`;
 		warning ( $warningMsg );
 		return false;
 	}
	return true;

**Comment by annatisch** [comment]
Thanks @hirtanak - the code snippet that's pasted above is not from our plugin - are there any other errors printed in the Maya script window/console output? Or any error messages displayed in the UI?

**Comment by hirtanak** [comment]
@annatisch sorry for slow response. This is we can only see the time of clear installation and load plugin and then use first time. Once quit the Maya and restart and reload plugin works well.
